### ISSUE TITLE
BUG: point disapear after change amount of lagre xDistance suddenly

### ISSUE THREAD

**Issue by TrdHuy** [TrdHuy/RICHY_DevTool#32]
### Checks

- [X] I have checked that this issue has not already been reported.

- [X] I am using the latest version of RICHY.

### Problem Description

we should redraw all point from currentStartIndex -> currentEndIndex, this has same or maybe better performance with previous workaround

### To Reproduce

1. ...
2. ...
3. ...

### Screenshots

https://github.com/TrdHuy/RICHY_DevTool/assets/32306489/6c311009-ebfe-455b-b083-e7adc4926711

### RICHY Version

0

### Windows Build Number

any

### Occurred branch name

master

### Error Log

<details>

```shell

Replace this line with the important log contents.

```
</details>

**Comment by BalalaX** [comment]
ISSUE STILL HAPPEN

https://github.com/TrdHuy/RICHY_DevTool/assets/144693599/f81545a0-f992-4e3b-9675-1cf154b07c29
